# vim ft=yaml
# https://travis-ci.org/leeclemens/imageroller
language: python
python:
  - 3.4
  - 3.5
before_install:
  - travis_retry sudo apt-get update -qq
  # Set this so sudo executes the correct python binary
  #   Anything not using sudo will already have the correct environment
  - export VENV_BIN="$VIRTUAL_ENV/bin" && echo "VENV_BIN set to $VENV_BIN"
install:
  # Install Python packages / dependencies
  - sudo $VENV_BIN/pip install .
matrix:
  fast_finish: true
